Next: while文を追加
aiscript-dev/aiscript pull request #674
Opened 2024-05-17 03:28 UTC by FineArchs

# What

while文とdo-while文を追加します。
実装を簡略化するためにloop+if+breakの糖衣構文にしています。
# Why

#42
# Additional info (optional)

後でテストとドキュメントを追加します

2024-05-28 11:11 UTC, salano-ym approved these changes

2024-05-28 11:21 UTC, uzmoi requested changes

2024-05-28 11:41 UTC, FineArchs commented on docs/syntax.md
> +} // hoge
あれ、本当だ…うっかりしてました。ありがとうございます

2024-05-28 11:53 UTC, uzmoi approved these changes

2024-06-03 23:09 UTC, FineArchs commented
条件を満たしていたのでマージします。

2024-06-03 23:09 UTC, merged