ドキュメントの移行
aiscript-dev/aiscript pull request #869
Opened 2024-11-30 08:42 UTC by FineArchs

# What

#804 における新規ドキュメンテーションサイトの開設に伴い、既存のドキュメントを（開発用のものを除き）削除します。
代わりにその旨を記したREADME.mdを配置します。
また、READMEのリンクの更新を行います。

2024-11-30 08:58 UTC, FineArchs commented
大きい変更なので2名のapproveをもってマージします。

2024-11-30 10:05 UTC, takejohn requested changes

2024-12-01 06:21 UTC, takejohn approved these changes

2024-12-01 06:40 UTC, uzmoi approved these changes

2024-12-02 08:29 UTC, merged